export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_FAILURE = "FETCH_FAILURE";
export const FETCH_BY_ID_SUCCESS = "FETCH_BY_ID_SUCCESS";
export const RESET_SELECT_PRODUCT = "RESET_SELECT_PRODUCT";
export const SET_USER_DATA = 'SET_USER_DATA';
export const ENQUEUE_SNACKBAR = 'ENQUEUE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
export const EMPTY_SELECT_PRODUCT = 'EMPTY_SELECT_PRODUCT';
export const INITIALIZED_SUCCESS = 'INITIALIZED_SUCCESS';

export const baseURL = "https://rent-car-back.herokuapp.com/";
